# Generated by Django 6.0.2 on 2026-02-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("opened_on", models.DateField(auto_now_add=True)),
                ("closed_on", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="Open", max_length=50)),
                ("priority", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("note", "General Note"),
                            ("received", "Letter Received"),
                            ("sent", "Letter Issued"),
                            ("discussion", "Discussion"),
                            ("meeting", "Meeting"),
                            ("update", "Update"),
                        ],
                        max_length=20,
                    ),
                ),
                ("short_note", models.CharField(max_length=300)),
                ("detailed_note", models.TextField(blank=True)),
                ("file_name", models.CharField(blank=True, max_length=200)),
                ("letter_no", models.CharField(blank=True, max_length=200)),
                ("letter_date", models.DateField(blank=True, null=True)),
                ("sender", models.CharField(blank=True, max_length=300)),
                ("sender_address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="issues.issue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("N", "Notesheet"),
                            ("C", "Correspondence"),
                            ("V", "Volume"),
                            ("P", "Page"),
                            ("F", "Flag"),
                            ("O", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                ("ref_value", models.CharField(max_length=50)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="issues.event",
                    ),
                ),
            ],
        ),
    ]
