# Generated by Django 6.0.3 on 2026-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_tag_issue_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_no", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("efile_no", models.CharField(blank=True, max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("remark", models.TextField(blank=True)),
                ("physical_location", models.CharField(blank=True, max_length=200)),
                ("section", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Closed", "Closed"),
                            ("Archived", "Archived"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("open_date", models.DateField(blank=True, null=True)),
                ("close_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="files",
            field=models.ManyToManyField(blank=True, to="issues.file"),
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.ManyToManyField(blank=True, to="issues.filetag"),
        ),
    ]
