# Generated by Django 6.0.3 on 2026-03-17 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_file_filetag_issue_files_file_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="file_name",
        ),
        migrations.AddField(
            model_name="event",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="issues.file",
            ),
        ),
    ]
