# Generated by Django 6.0.3 on 2026-03-19 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_remove_event_file_name_event_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="current_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="FileMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        max_length=10,
                    ),
                ),
                ("from_location", models.CharField(blank=True, max_length=200)),
                ("to_location", models.CharField(blank=True, max_length=200)),
                ("remark", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="issues.file",
                    ),
                ),
            ],
        ),
    ]
