# Generated by Django 6.0.3 on 2026-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_file_current_location_filemovement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="current_location",
        ),
        migrations.AddField(
            model_name="file",
            name="last_movement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="last_movement_remark",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="file",
            name="movement_status",
            field=models.CharField(
                choices=[("received", "Received"), ("sent", "Sent")],
                default="received",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="FileMovement",
        ),
    ]
